### ISSUE TITLE
Mounts still getting lost

### ISSUE THREAD

**Issue by lnevo** [mbb10324/MountUp#3]
Hi, I'm still having issues where it's losing the mounts. Definitely related to zoning, but I'm seeing it constantly while farming seeds in Emerald Dream.

**Comment by mbb10324** [comment]
Odd, I played the past couple days and haven't seen any errors again, or had any issues mounting. Although I have not spent much time in the emerald dream, ill try and spend some time around there tomorrow and see if I can replicate the issue. If you could, can you describe in further detail what your experiencing? Are you still getting the lua error, or just not able to mount and does it happen when transitioning between certain zones; if so can you provide the zone/sub-zone?  Thanks!

**Comment by lnevo** [comment]
Sorry for the delay, there has been no more LUA errors. It is definitely still happening and mostly after a zone. For example doing digs in Zaralek or coming out of an instance (or in). Not sure it's related but trying to mount up during the Tindrall fight I've had to use a hard-coded button.

**Comment by lnevo** [comment]
is there some debug we can enable that when it happens I can /mountup dump and get some variable states. I just had an occurrence on first login so it's starting to get inconvenient

**Comment by mbb10324** [comment]
Sorry, I haven't been able to play for a bit, will be getting back into it starting tomorrow. The problem is difficult to diagnose for me, because the addon is working fine for me, I've tried limit testing under multiple conditions and spamming the macros when leaving/entering zones etc, and everything is working as it should for me. To help me out a bit more if you don't mind telling me what kind of cpu your using in your computer, and how many mounts you have. The last thing I can think of is that possibly you a.) Have many mounts and its taking the addon a long time to traverse them all and give you a random mount, or b.) You have a low power cpu that is struggling to compute the randomization process. The addon should be optimized to a point where regardless if you had every mount in the game it can handle it, and if you can run the game then your cpu should be enough, but maybe there is something I have missed, or can try optimizing.
